{% set name = "underworld" %}
{% set version = "2.14.0" %}
{% set sha256 = "fdc6c7ae1034b5bd6159b465ae44d75a19ca9bb44021e9d16c9eafb6bced2e12" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/julesghub/underworld2.git
  git_rev: dockerfile-updates
    #  url: https://github.com/underworldcode/underworld2/archive/refs/tags/v{{ version }}b.tar.gz
    #  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  script: PETSC_DIR=$PREFIX {{ PYTHON }} -m pip -vv install --no-deps .  
  missing_dso_whitelist:
    - libm.so.6 
    - libc.so.6 

requirements:

  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}

  host:
    - pkg-config
    - pip
    - python
    - libxml2
    - numpy >=1.18
    - cmake
    - swig >=4.0.0
    - ninja
    - petsc {{ petsc }}
    - {{ mpi }}

  run:
    - python
    - {{ mpi }}
    - numpy
    - petsc {{ petsc }}
    - pint
    - scipy
    - mpi4py
    - h5py

test:
  requires:
    - pytest
    - matplotlib

  source_files:
    - docs/pytests
    - docs/user_guide
    - docs/examples

  commands:
    - python -X faulthandler -c "import underworld; underworld.mesh.FeMesh_Cartesian();"
    - pytest -vvv docs/pytests


about:
  home: "https://github.com/underworldcode/underworld2"
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:  LGPLv3.txt
  summary: "Geodynamics API"
  doc_url: https://underworld2.readthedocs.io
  dev_url: https://github.com/underworldcode/underworld2/tree/development

extra:
  recipe-maintainers:
    - rbeucher
    - julesghub
    - lmoresi
