name: docker images build

on:
  push:
    branches:
      - 'development'
      - 'new_ci'
  workflow_dispatch:

jobs:
  build_petsc_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Petsc Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docs/development/docker/petsc/Dockerfile
  
  build_lavavu_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Lavavu Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docs/development/docker/lavavu/Dockerfile
  
  build_base_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Base Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docs/development/docker/base/Dockerfile
