on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Global Protect
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect
        uses: "./actions/globalprotect"
        env:
          USER: ${{ secrets.GB_USER }}
          PASS: ${{ secrets.GB_PASSWORD }}
          SERVER: ${{ secrets.GB_SERVER }}
      - name: Connect to Kaiju
        run: |
            sshpass -p ${{secrets.KAIJU_PASSWORD}} ssh -tt -oStrictHostKeyChecking=no ${{secrets.KAIJU_USERNAME}}@kaiju.anu.edu.au
            mkdir this_was_created_by_action
      - name: Checkout
        uses: actions/checkout@v2
           
